language: java

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script: gradle build -Dspring.profiles.active=localdev-test 

jdk:
- oraclejdk8

after_success:
- gradle jacocoTestReport jacocoIntegrationTestReport sonarqube --stacktrace
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
- bash <(curl -s https://codecov.io/bash)
- coveralls

notifications:
  webhooks: https://acichon89-fantacalcio.getbadges.io/api/app/webhook/485782e5-7a9c-4f2a-8465-9b6f642907f7
