language: java

script: gradle build --info -Dspring.profiles.active=remotetest

jdk:
- oraclejdk8

after_success:
- gradle jacocoTestReport sonarqube --stacktrace
- bash <(curl -s https://codecov.io/bash)
