server:
  port: 7777
  context-path: /uaa

spring:
  datasource:
    url: jdbc:mysql://localhost/fantacalciodb_user
    username: fantacalcio_user
    password: fanta123
    driverClassName: com.mysql.jdbc.Driver
