zuul:
  routes:
    users:
      path: /user/**
      serviceId: fantacalcio-coredomain-user
      stripPrefix: false
    auth:
      path: /oauth/**
      serviceId: fantacalcio-auth-server
      stripPrefix: false
  prefix: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/