server:
  port: 8070
spring:
  cloud:
    stream:
      bindings:
        removeTokenChannel:
          destination: remove-oauth-token-queue
          contentType: text/plain
        activationMailChannel:
          destination: confirmation-mail-queue
          contentType: text/plain